### ISSUE TITLE
Support RLE (Run Length Encoding)

### ISSUE THREAD

**Issue by epilys** [embedded-graphics/tinybmp#17]
- Version of tinybmp in use (if applicable): 0.3.1 and `master`

## Description of the problem/feature request/other

`RawBmp::from_slice` fails on this file.

## Test case (if applicable)

```rust
    let mut bmp_file = File::open("david.bmp").unwrap();
    let mut bytes = vec![];
    bmp_file.read_to_end(&mut bytes).unwrap();
    let bmp = RawBmp::from_slice(&bytes).unwrap();
```

File gzipped because github doesn't allow BMP uploads: [david.bmp.gz](https://github.com/embedded-graphics/tinybmp/files/7652063/david.bmp.gz)

**Comment by rfuest** [comment]
Your image file is RLE compressed, which isn't yet supported by tinybmp.

**Comment by thejpster** [comment]
Added in #42

**Comment by thejpster** [comment]
I think this is now done?
