### ISSUE TITLE
Color palette not parsed correctly for 1BPP images

### ISSUE THREAD

**Issue by jcard0na** [embedded-graphics/tinybmp#18]
- Version of tinybmp in use (if applicable): 0.3.1

## Description of the problem/feature request/other

tinybmp does not display correctly negative images of depth 1.  (I did not test other depths).
If you take an 1bpp image and negate it (for instance, with ImageMagick -negate command), the new image will appear identical to the original when displayed by tinybmp.  The problems seems to be in the parsing of the color table, as negating an image just "flips" the colors in the table, leaving the individual pixels unchanged.

## Test case 

1. Create two test images with ImageMagick
```
convert -size 200x200 canvas:black -type bilevel  images/black.bmp
convert -size 200x200 canvas:white -type bilevel  images/white.bmp
```
2. Modify the tinybmp example to display these images.  Below are the changes to show `white.bmp`
```
diff --git a/eg-0.7/examples/image-bmp.rs b/eg-0.7/examples/image-bmp.rs
index bef1103..f65941d 100644
--- a/eg-0.7/examples/image-bmp.rs
+++ b/eg-0.7/examples/image-bmp.rs
@@ -8,17 +8,17 @@
 //! The `graphics` feature of `tinybmp` needs to be enabled in `Cargo.toml` to use the `Bmp` object
 //! with embedded-graphics.
 
-use embedded_graphics::{image::Image, pixelcolor::Rgb565, prelude::*};
+use embedded_graphics::{image::Image, pixelcolor::BinaryColor, prelude::*};
 use embedded_graphics_simulator::{OutputSettingsBuilder, SimulatorDisplay, Window};
 use tinybmp::Bmp;
 
 fn main() -> Result<(), core::convert::Infallible> {
-    let mut display: SimulatorDisplay<Rgb565> = SimulatorDisplay::new(Size::new(128, 128));
+    let mut display: SimulatorDisplay<BinaryColor> = SimulatorDisplay::new(Size::new(128, 128));
 
     // Load the BMP image.
     // The color type must be specified explicitly to match the color format used by the image,
     // otherwise the compiler may infer an incorrect type.
-    let bmp: Bmp<Rgb565> = Bmp::from_slice(include_bytes!("./assets/rust-pride.bmp")).unwrap();
+    let bmp: Bmp<BinaryColor> = Bmp::from_slice(include_bytes!("./assets/white.bmp")).unwrap();
 
     // To draw the `bmp` object to the display it needs to be wrapped in an `Image` object to set
     // the position at which it should drawn. Here, the top left corner of the image is set to
```
3. Observe a black image instead of the expected white.
![image](https://user-images.githubusercontent.com/676181/158372244-e8072c8d-7b49-41a0-a2fa-afe22f67367a.png)
4. Compare the images and observe that they only differ in the color table (offset 0x7a in header)
![image](https://user-images.githubusercontent.com/676181/158373578-55695ea9-2ec1-4b65-bcb0-a4a0f25f0fd9.png)

**Comment by jamwaffles** [comment]
Thanks for the detailed issue report! I can make my own image, but for completeness sake would you be able to post the image file you're having issues with so it's easier to reproduce the error?

**Comment by jcard0na** [comment]
Sure!  For instance, you can try with these two images attached.
![image](https://user-images.githubusercontent.com/676181/158446254-5395d406-a2bf-4401-b2bf-18ebfd20745d.png)
[images.zip](https://github.com/embedded-graphics/tinybmp/files/8256181/images.zip)

**Comment by jcard0na** [comment]
For more details, here is how the above images appear on the simulator:
![image](https://user-images.githubusercontent.com/676181/158447128-45536703-bd27-4e67-9985-64c24df9bb58.png)

And this is the modified example that produces that image:
```rust
//! # Example: BMP images
//!
//! Draw a 16BPP BMP image of the Rust logo to a display
//!
//! This example uses the [tinybmp](https://crates.io/crates/tinybmp) crate to load the BMP from a
//! byte slice read in at compile time.
//!
//! The `graphics` feature of `tinybmp` needs to be enabled in `Cargo.toml` to use the `Bmp` object
//! with embedded-graphics.

use embedded_graphics::{image::Image, pixelcolor::BinaryColor, prelude::*};
use embedded_graphics_simulator::{OutputSettingsBuilder, SimulatorDisplay, Window};
use tinybmp::Bmp;

fn main() -> Result<(), core::convert::Infallible> {
    let mut display: SimulatorDisplay<BinaryColor> = SimulatorDisplay::new(Size::new(400, 200));

    // Load the BMP image.
    // The color type must be specified explicitly to match the color format used by the image,
    // otherwise the compiler may infer an incorrect type.
    let bmp: Bmp<BinaryColor> = Bmp::from_slice(include_bytes!("./assets/light.bmp")).unwrap();

    // To draw the `bmp` object to the display it needs to be wrapped in an `Image` object to set
    // the position at which it should drawn. Here, the top left corner of the image is set to
    // `(32, 32)`.
    let image = Image::new(&bmp, Point::new(0, 0));

    // Display the image
    image.draw(&mut display)?;

    let bmp: Bmp<BinaryColor> = Bmp::from_slice(include_bytes!("./assets/nolight.bmp")).unwrap();

    // To draw the `bmp` object to the display it needs to be wrapped in an `Image` object to set
    // the position at which it should drawn. Here, the top left corner of the image is set to
    // `(32, 32)`.
    let image = Image::new(&bmp, Point::new(200, 0));

    // Display the image
    image.draw(&mut display)?;

    let output_settings = OutputSettingsBuilder::new().scale(2).build();
    Window::new("BMP image", &output_settings).show_static(&display);

    Ok(())
}
```

**Comment by jamwaffles** [comment]
Thanks again for taking the time to provide files, details and test cases. This made reproducing and fixing this issue so much easier. 

I have a fix available in #19. If you're interested in testing that PR out in your own code and reporting back, that would be a great confirmation.

**Comment by jcard0na** [comment]
Tested it both on simulator and embedded target (STM32) and fix works on both.  Thanks for the quick fix!
![image](https://user-images.githubusercontent.com/676181/158988581-d3d30b51-5fef-48f3-98ec-a337913ad380.png)

**Comment by jamwaffles** [comment]
Great, thanks for confirming!

**Comment by jamwaffles** [comment]
This is released in version [0.3.2](https://crates.io/crates/tinybmp/0.3.2).

**Comment by Dominaezzz** [comment]
With the new version, [this 1bpp image](https://raw.githubusercontent.com/waveshare/IT8951-ePaper/de567d4fcae15925308483a49be7e93d9d9d29b9/pic/800x600_gif_0.bmp) now comes out as completely black. Was scratching my head for a while.

I'm using this.
```
let image = Bmp::<BinaryColor>::from_slice(&frame[0..]).expect("Should load fine");
for Pixel(coord, color) in image.pixels() {
    let pixel = if color.is_on() { 1 } else { 0 };
    // Upload pixel to E-Ink display.
    // pixel is now always 1.
}
```

**Comment by jamwaffles** [comment]
Thanks for posting a sample image to check with. I did some debugging and the colour table in your image only has one entry:

```
[src/raw_bmp.rs:108] color_table = ColorTable {
    data: [
        0,
        0,
        0,
        0,
    ],
}
```

This means that when `color` is `1`, there is no entry for the pixel colour in the table, so `tinybmp` defaults to `0` (off). @rfuest is this an issue with the BMP or `tinybmp`?

**Comment by rfuest** [comment]
The issue is caused by this line: https://github.com/embedded-graphics/tinybmp/blob/2e9de3e9152e9e88686585dcd0e2480394087190/src/header/dib_header.rs#L91 It calculates `BPP^2` instead of the correct `2^BPP`.

**Comment by jamwaffles** [comment]
@Dominaezzz This should hopefully be fixed in the just-released [0.3.3](https://crates.io/crates/tinybmp/0.3.3). Can you do a `cargo update` and check your image again please?

**Comment by Dominaezzz** [comment]
Just ran my project with `0.3.3` and it works now!

Thanks for fixing this so promptly!

**Comment by jamwaffles** [comment]
Great news! Thanks for bearing with us :)
