### ISSUE TITLE
Update master changelog from 0.3 branch

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/tinybmp#27]
Just a reminder that the 0.3.3 release isn't yet added to the master changelog.

**Comment by jamwaffles** [comment]
Oops. I knew I'd mess something up. Fixed in 815e9f99aa5ce053b4985572ea145f39758e78a5 - a cherry pick from `v0.3.x`. I pushed it straight to `master` as I didn't think there was anything worth reviewing in it. Please reopen this issue if you think otherwise though.
