### ISSUE TITLE
Accessing individual pixels without copying the buffer

### ISSUE THREAD

**Issue by mbuesch** [embedded-graphics/tinybmp#33]
Is there a way to directly access random pixel data with a non-iterative random access pattern without copying into a Vec?

I want to use the bitmap as a kind of simple data structure.
For that I need random access to pixels. The iterator approach doesn't work and collect()ing the iterator wastes memory.

I'm thinking of an API such as:

```rust
impl RawBmp {
    fn get_pixel(&self, x: u32; y: u32) -> Pixel {
        ...
    }
}
```

Thanks a lot for your help.

**Comment by rfuest** [comment]
I've just opened #34 to add this feature.

**Comment by mbuesch** [comment]
@rfuest Thanks.
But you still seem to be using Iterator instead of direct O(1) access to the raw data.
Isn't Iterator::nth() horribly expensive for random accesses?
