### ISSUE TITLE
Unable to get the compression info

### ISSUE THREAD

**Issue by asimaranov** [embedded-graphics/tinybmp#6]
My device does not support compressed bmp images and I want to check whether the images are compressed or not. The compression info is not stored in the headers struct
```rust
pub fn parse_header(input: &[u8]) -> IResult<&[u8], Header> {
   ...
    let (input, bpp) = le_u16(input)?;
    let (input, _compression_method) = le_u32(input)?;  // The issue
    let (input, image_data_len) = le_u32(input)?;  
    ...
```
How can I get the compression info, and why the _compression_method is not stored in the struct?

**Comment by rfuest** [comment]
This has changed after the last stable release of tinybmp. In the `master` version the parsing of the header fails if the BMP file is RLE compressed.

Do you use `tinybmp` standalone or with `embedded-graphics`? If you use it standalone I would suggest that you try the latest alpha version.

But this version isn't compatible with `embedded-graphics` 0.6, so you might have to use a workaround if you don't want to use unstable versions for everything. You could check the compression field manually, after you have parsed the BMP file:
```rust
let data = include_bytes!("../tests/chessboard-8px-24bit.bmp");
let bmp = Bmp::from_slice(data).expect("Failed to parse BMP image");

let compression = u32::from_le_bytes(data[30..34].try_into().unwrap());
if compression != 0 && compression != 3 {
    panic!("File is compressed");
}
```

**Comment by asimaranov** [comment]
My device also fails if the compression equals to 3 and I want to check it also. This workaround will work, but what is the reason for dropping the compression info? Another offtopic question, you don't know by chance if it is possible to create a rgba bmp file that's compression equals to 0? Gimp and paint .net generates bmp with 3 compression, which my device does not support

**Comment by rfuest** [comment]
> This workaround will work, but what is the reason for dropping the compression info?

I'm not sure, it was ignored since before I started working on `tinybmp`. But, as I said, the next version of `tinybmp` will read the compression field to handle type 3 correctly. In this case we don't need to store the compression type, because parsing fails if compression is enabled and the new `channel_masks` field contains all necessary information to decode any type 0 or 3 image.

> Another offtopic question, you don't know by chance if it is possible to create a rgba bmp file that's compression equals to 0? Gimp and paint .net generates bmp with 3 compression, which my device does not support

Maybe ImageMagick would be able to output a type 0 image, but I haven't tried it. How exactly does type 3 fail in you application? Because a type 3 image should be usable in the same way as a type 0 image, if you know the correct byteorder.

**Comment by asimaranov** [comment]
Ok, thanks. I use it for my pocketbook game, and I have no idea why it don't support the type 3. Device just doesn't render bmp's if it's type equal 3. The original resource packer allows only type 0 bmps too
![image](https://user-images.githubusercontent.com/25568730/106367042-fc846280-6350-11eb-9b4f-a621feb4a02e.png)

![image](https://user-images.githubusercontent.com/25568730/106366970-59334d80-6350-11eb-8478-b89d891554ca.png)

**Comment by rfuest** [comment]
Did you try to convert the image to grayscale or 1bpp black and white before exporting the BMP file with GIMP (In the menu: Image -> Mode -> Grayscale or Image -> Mode -> Indexed... -> Use black and white (1-bit) palette)?
